### ISSUE TITLE
Masking isn't applied when filtering.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#104] opened 2022-04-12 08:34 UTC
# Describe the bug

On the `dev` branch I've been working on implementing tests for each of the steps involved in filtering and have encountered some perhaps unintended behaviour that arises during masking of NumPy arrays and their subsequent usage.

# To Reproduce

The tests use a randomly generated image and run each method against it to obtain the expected results. I can then write a test and compare the method against this result, future changes which return incorrect results mean the tests will fail and flag up problems.

When it comes to masking the data and recalculating the row and column quantiles on my system (Python `3.10.4`; NumPy `1.22.3`) I get a warning raised...

```bash
tests/test_filters.py::test_row_col_quantiles_with_mask
  /home/neil/.virtualenvs/topostats/lib/python3.10/site-packages/numpy/lib/function_base.py:4650: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
    arr.partition(
```

The warning doesn't prevent the test from passing because the array I'm comparing the calculated row/column quantiles against is calculated in the same way (tests have to have a starting point).

However, the test failed on GitHub Actions as the arrays are different, see the logs [here](https://github.com/AFM-SPM/TopoStats/runs/5975276899?check_suite_focus=true). Investigating this the Python version is `3.7.12` and the NumPy version is `1.21.5` but I don't think this is the root cause of the problem because it is only the observed warning that is a relatively new feature, masked arrays have never excluded the masked values when calculating quantiles using `np.quantile()` (which in turn calls `np.partition()` as part of its calculations). This is detailed in the bugs...

* [#14716 np.quantile does not ignore masked values with masked_arrays](https://github.com/numpy/numpy/issues/14716)
* [#4767 percentile for masked array](https://github.com/numpy/numpy/issues/4767)

...and there is an open [pull request #15180](https://github.com/numpy/numpy/pull/15180) for handling it.

The more immediate issue is what the intended behaviour within the reworking of TopoStats on the `dev` branch should be.

My understanding of the process so far on the code I've refactored is that the steps taken are to...

1. Extract image height values.
2. Flatten the image which involves two steps performed on unmasked data...
    * Align Rows (no mask)
    * Remove Tilt (no mask)
3. Calculate a threshold from this initial flattening.
4. Mask pixel heights that exceed the threshold.
5. Flatten the image again but on masked data...
    * Align Rows (mask)
    * Remove Tilt (mask)
6. Additional steps applied (such as removing bowing and gaussian filters).

**NB** Both the Align Rows and Remove Tilt steps calculate the row and column quantiles calling `row_col_quantiles()`, but conditionally apply a mask if one is provided before doing so.

The problem we have currently as described above is that whilst a mask is created at step 4 it isn't applied when flattening the image in step 5. The mask is passed from the `align_rows()` and `remove_tilt()` functions to the `row_col_quantiles()` function and it is applied `if mask is not None:` (related issue is #95 where @ns-rse mistakenly converted this to a `boolean`), but NumPy doesn't apply this since `partition()` (called by `np.quantiles()`) ignores the mask (silently under Python `3.7.*`/NumPy `1.21.5` but with a warning under Python `3.10.*`/NumPy `1.22.3`).

I think the intended behaviour _is_ to calculate the quantiles with masking and this is possible (with solutions provided in [#4767](https://github.com/numpy/numpy/issues/4767)). Would you be able to clarify this please @SylviaWhittle 

Two further related things...

1. I'm curious whether the 25th and 75th percentiles need to be calculated as so far I've not seen them being used, its only the median (50th percentile) that I've seen used, if they're not required we can avoid calculating them in the first place.

2. I notice also that a mask is applied and then `np.mean()` called against the masked array in the `remove_x_bowing()` function on the `dev-remove-gwyiddon` branch (see [lines 138-146](https://github.com/AFM-SPM/TopoStats/blob/dev-remove-gwyddion/topostats/filters.py)) so this is likely affected here but a more direct solution is available via [`np.ma.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.ma.mean.html).

I should also say that I've never used [NumPy masked arrays](https://numpy.org/doc/stable/reference/maskedarray.html) before so this is all new to me too!

**Comment by SylviaWhittle** [comment] 2022-04-12 09:12
I will set up a meeting to discuss this, however here are some points for posterity @ns-rse :

- You are correct about the intended behaviour
- The 25th and 75th percentiles are not used, I added them thinking that they may be useful and then never went back and removed them - they are free to remove, although when reading the code, a function named `row_col_quantiles`, I would think it would return more than just the median, hence the index of [1] applied makes more sense to readers? If we remove the 25th and 75th, perhaps we should rename the function to `row_col_medians`?
- The np.ma.mean() would be preferable, I didn't notice that this is a method.
- I am very new to the masked arrays too, so if something seems odd, then it's a mistake, and if you find a better way of doing something, then change it :) 
- The bug does not occur on my system : Python 3.10.1 64-bit, Numpy 1.21.5. Is there anything in addition to matching python and numpy versions that I can do to replicate this bug?

**Comment by ns-rse** [comment] 2022-04-12 16:43
Thanks @SylviaWhittle that is all really useful.

* Removing the 25th and 75th percentiles and renaming the function would be sensible if they're not required, on a per-image basis the difference probably won't be that noticeable, if at all (depends on the image size), but if there are a large number of images being processed this can add up. Either `row_col_median()` would be fine or removing the plural and making it `row_col_quantile()` just as `np.quantile()` can calculate a range of values.
* Glad to know I'm not alone on being new to masking. I only discovered the `np.ma.mean()` function after reading documentation this morning.

I've been doing some more investigation on this intermittently today and it appears that the Open issues I found haven't been resolved. The code I've used to check this is...

```python
import numpy as np

RNG = np.random.default_rng(seed = 3892398)
SMALL_ARRAY_SIZE = (3, 3)

small_array = RNG.random(SMALL_ARRAY_SIZE)
mask = RNG.uniform(low=0, high=1, size=SMALL_ARRAY_SIZE) > 0.5

small_array_masked = np.ma.masked_array(small_array, mask, fill_value=np.nan)

print(f'WITHOUT MASK')
print(f'small_array                                   :\n{small_array}')
print(f'np.quantile(small_array, [0.5])               : {np.quantile(small_array, [0.5], axis=1).T}')
print(f'np.median(small_array)                        : {np.median(small_array, axis=1).T}')

print(f'WITH MASK')
print(f'small_array_masked                                   :\n{small_array_masked}')
print(f'np.quantile(small_array_masked, [0.5])               : {np.quantile(small_array_masked, [0.5], axis=1).T.data}')

WITHOUT MASK
small_array                                   :
[[0.55893194 0.58423965 0.54991388]
 [0.36399804 0.06721005 0.02255171]
 [0.41724214 0.33160048 0.66949514]]
np.quantile(small_array, [0.5])               : [[0.55893194]
                                                 [0.06721005]
                                                 [0.41724214]]
np.median(small_array)                        : [0.55893194 0.06721005 0.41724214]
WITH MASK
small_array_masked                                   :
[[0.5589319369888012 0.5842396462969964 0.549913882332871]
 [0.3639980357139009 0.06721005487309961 --]
 [0.41724213939486854 -- --]]
/home/neil/.virtualenvs/default/lib/python3.10/site-packages/numpy/lib/function_base.py:4650: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  arr.partition(
np.quantile(small_array_masked, [0.5])               : [[0.55893194]
                                                        [0.36399804]
                                                        [0.66949514]]
/home/neil/.virtualenvs/default/lib/python3.10/site-packages/numpy/core/fromnumeric.py:758: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
np.median(small_array_masked)                        : [0.55893194 0.06721005 0.        ]
```

What is strange (to me) is the result of `np.quantile(small_array_masked, [0.5])` because I would expect the first row median to be the `0.558931` as it is, the second row should be half-way between the two values (because the third is masked), i.e. `0.215604` but its not its the upper value. The third row I would expect to be `0.417242` since there is only one observation and the others are masked.  This is under Python `3.10.*`.

Thank you for the offer of help with debugging this, I've managed to replicate the bug locally as I've created a virtual environment that uses Python `3.7` and Numpy `1.21.*` which match those used when GitHub Actions run `pytest` and run the tests under this environment and Python `3.10.*`/NumPy `1.22.3` and they pass locally on the later but fail on the former, just as they do on GitHub's Actions, even though the smaller test illustrated above passes.

Running the sample code above under Python `3.7.*` gives what I would expect...

```python
WITHOUT MASK
small_array                                   :
[[0.55893194 0.58423965 0.54991388]
 [0.36399804 0.06721005 0.02255171]
 [0.41724214 0.33160048 0.66949514]]
np.quantile(small_array, [0.5])               : [[0.55893194]
 [0.06721005]
 [0.41724214]]
np.median(small_array)                        : [0.55893194 0.06721005 0.41724214]
WITH MASK
small_array_masked                                   :
[[0.5589319369888012 0.5842396462969964 0.549913882332871]
 [0.3639980357139009 0.06721005487309961 --]
 [0.41724213939486854 -- --]]
np.quantile(small_array_masked, [0.5])               : [[0.55893194]
                                                        [0.06721005]
                                                        [0.41724214]]
/home/neil/miniconda3/envs/topostats/lib/python3.7/site-packages/numpy/core/fromnumeric.py:755: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
np.median(small_array_masked)                        : [0.5589319369888012 0.06721005487309961 --]
```

It may well be down to the `method` that is used in calculating the median and that is perhaps something we can discuss tomorrow as there may be something informative from Gwyddion.

Thank you very much for taking the time to look at this and clarify the steps I was querying :+1: Look forward to chatting tomorrow and hopefully we can get to the bottom of this.

**Comment by SylviaWhittle** [comment] 2022-11-23 12:21
Closing as the this code has all been replaced as of #351

**Closed by SylviaWhittle** 2022-11-23 12:21 UTC
Labels: bug
